name: "Validation"

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha"
  release:
    - published

jobs:
  encoding:
    uses: "HaneulCheong/golden-oak-library/.github/workflows/encoding.yml@main"
